# Generated by Django 2.2.16 on 2021-09-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210904_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinate', to='workers.Worker', verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Руководитель'), (2, 'Заместитель'), (3, 'Начальник отдела'), (4, 'Заместитель начальника отдела'), (5, 'Рабочий')], default=1, verbose_name='Должность'),
        ),
    ]
